"""got rid of user answer table

Revision ID: 4d8e9972337c
Revises: e31903151b3b
Create Date: 2018-04-20 16:33:37.390102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8e9972337c'
down_revision = 'e31903151b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('incorrect', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='answers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    # ### end Alembic commands ###
